export const templateCategories = ["Birthday", "Kids", "Princess", "Sports", "Space", "Animals", "Floral", "Baby"] as const;
export type TemplateCategory = (typeof templateCategories)[number];
export type TemplateDefinition = { id: string; name: string; category: TemplateCategory; tags: string[]; thumbnail: string; masterImage: string };
const template = (id: string, name: string, category: TemplateCategory, tags: string[]): TemplateDefinition => ({ id, name, category, tags, thumbnail: `/templates/thumbnails/${id}.jpg`, masterImage: `/templates/masters/${id}.png` });
export const editorTemplates: readonly TemplateDefinition[] = [
  template("classic-balloon-birthday", "Classic Balloon Birthday", "Birthday", ["balloon", "classic", "party", "colorful"]),
  template("colorful-confetti-party", "Colorful Confetti Party", "Birthday", ["confetti", "streamers", "bright", "party"]),
  template("golden-birthday-celebration", "Golden Birthday Celebration", "Birthday", ["gold", "elegant", "luxury", "sparkles"]),
  template("rainbow-birthday-party", "Rainbow Birthday Party", "Birthday", ["rainbow", "balloons", "clouds", "colorful"]),
  template("pastel-birthday-celebration", "Pastel Birthday Celebration", "Birthday", ["pastel", "soft", "balloons", "party"]),
  template("star-birthday-party", "Star Birthday Party", "Birthday", ["stars", "night", "gold", "party"]),
  template("birthday-cake-celebration", "Birthday Cake Celebration", "Birthday", ["cake", "candles", "dessert", "party"]),
  template("gift-box-party", "Gift Box Party", "Birthday", ["gift", "present", "ribbon", "surprise"]),
  template("bright-kids-birthday", "Bright Kids Birthday", "Birthday", ["kids", "bright", "playful", "balloons"]),
  template("elegant-birthday-celebration", "Elegant Birthday Celebration", "Birthday", ["elegant", "floral", "gold", "celebration"]),
  template("dinosaur-jungle-birthday", "Dinosaur Jungle Birthday", "Kids", ["dinosaur", "jungle", "kids", "prehistoric"]),
  template("dinosaur-party", "Dinosaur Party", "Kids", ["dinosaur", "party", "confetti", "kids"]),
  template("baby-dinosaur-birthday", "Baby Dinosaur Birthday", "Kids", ["baby dinosaur", "cute", "pastel", "kids"]),
  template("jungle-adventure", "Jungle Adventure", "Kids", ["jungle", "adventure", "tropical", "animals"]),
  template("colorful-kids-party", "Colorful Kids Party", "Kids", ["kids", "colorful", "party", "playful"]),
  template("kids-rainbow-celebration", "Kids Rainbow Celebration", "Kids", ["kids", "rainbow", "clouds", "colorful"]),
  template("princess-fantasy-birthday", "Princess Fantasy Birthday", "Princess", ["princess", "castle", "crown", "fantasy"]),
  template("royal-crown-birthday", "Royal Crown Birthday", "Princess", ["royal", "crown", "jewels", "gold"]),
  template("magical-princess-party", "Magical Princess Party", "Princess", ["princess", "magic", "castle", "pastel"]),
  template("rainbow-unicorn", "Rainbow Unicorn", "Princess", ["unicorn", "rainbow", "fantasy", "colorful"]),
  template("unicorn-dream", "Unicorn Dream", "Princess", ["unicorn", "dream", "clouds", "pastel"]),
  template("butterfly-fantasy", "Butterfly Fantasy", "Princess", ["butterfly", "fantasy", "flowers", "sparkles"]),
  template("magical-stars-birthday", "Magical Stars Birthday", "Princess", ["stars", "moon", "magic", "sparkles"]),
  template("soccer-stadium-birthday", "Soccer Stadium Birthday", "Sports", ["soccer", "football", "stadium", "ball"]),
  template("basketball-birthday", "Basketball Birthday", "Sports", ["basketball", "hoop", "court", "arena"]),
  template("football-birthday", "Football Birthday", "Sports", ["football", "stadium", "game day", "sports"]),
  template("baseball-birthday", "Baseball Birthday", "Sports", ["baseball", "bat", "glove", "ballpark"]),
  template("sports-champion", "Sports Champion", "Sports", ["sports", "champion", "trophy", "medal"]),
  template("trophy-celebration", "Trophy Celebration", "Sports", ["trophy", "winner", "gold", "confetti"]),
  template("all-star-birthday", "All-Star Birthday", "Sports", ["all star", "sports", "balls", "champion"]),
  template("game-day-birthday", "Game Day Birthday", "Sports", ["game day", "sports", "stadium", "celebration"]),
  template("space-adventure", "Space Adventure", "Space", ["space", "planets", "galaxy", "rocket"]),
  template("rocket-birthday", "Rocket Birthday", "Space", ["rocket", "launch", "planets", "stars"]),
  template("moon-and-stars", "Moon and Stars", "Space", ["moon", "stars", "celestial", "night"]),
  template("outer-space-party", "Outer Space Party", "Space", ["space", "planets", "party", "galaxy"]),
  template("little-astronaut-adventure", "Little Astronaut Adventure", "Space", ["astronaut", "space", "rocket", "kids"]),
  template("safari-birthday", "Safari Birthday", "Animals", ["safari", "animals", "savanna", "jungle"]),
  template("lion-birthday", "Lion Birthday", "Animals", ["lion", "savanna", "animals", "kids"]),
  template("butterfly-garden", "Butterfly Garden", "Animals", ["butterfly", "garden", "flowers", "nature"]),
  template("cute-animal-party", "Cute Animal Party", "Animals", ["cute animals", "woodland", "party", "balloons"]),
  template("jungle-animals", "Jungle Animals", "Animals", ["jungle", "animals", "tropical", "foliage"]),
  template("floral-celebration", "Floral Celebration", "Floral", ["floral", "flowers", "botanical", "elegant"]),
  template("pink-flower-birthday", "Pink Flower Birthday", "Floral", ["pink", "flower", "roses", "floral"]),
  template("sunflower-birthday", "Sunflower Birthday", "Floral", ["sunflower", "yellow", "flower", "nature"]),
  template("butterfly-flowers", "Butterfly Flowers", "Floral", ["butterfly", "flowers", "garden", "nature"]),
  template("garden-birthday", "Garden Birthday", "Floral", ["garden", "flowers", "botanical", "birthday"]),
  template("baby-cloud-celebration", "Baby Cloud Celebration", "Baby", ["baby", "clouds", "pastel", "nursery"]),
  template("pastel-stars", "Pastel Stars", "Baby", ["pastel", "stars", "soft", "baby"]),
  template("little-rainbow", "Little Rainbow", "Baby", ["rainbow", "baby", "clouds", "pastel"]),
  template("sweet-hearts-birthday", "Sweet Hearts Birthday", "Baby", ["hearts", "sweet", "pink", "cute"]),
] as const;
